### ISSUE TITLE
Enhance the `json` reporter to also pass the `passthrough` object - like they added in the automate-json reporter

### ISSUE THREAD

**Issue by aaronlippold** [mitre/inspec#6]
https://github.com/inspec/inspec/issues/3181

The change for the automate-json reporter is here: https://github.com/inspec/inspec/pull/3906

As you can see - all we would really be doing is basically the same thing ... so 

perhaps this PR of ours would move the 'passthrough' part more generally to the 'json' reporter and then the 'automate-json' reporter would just inherit it. 

Right now this implementation is down one level to low in my openion.

**Comment by aaronlippold** [comment]
I think this issue is connected: https://github.com/inspec/inspec/issues/4605

**Comment by Amndeep7** [comment]
It seems like the functionality was added here: https://github.com/inspec/inspec/pull/5430

@aaronlippold please reopen the issue if there's more that needs to be done, but I'mma close it for now.
